### ISSUE TITLE
can't run deploy.py on ubuntu server 

### ISSUE THREAD

**Issue by Mikaeel-js** [EniasCailliau/GirlfriendGPT#31]
Hi I can't run deploy 

when i run command python3 deploy.py

I get this :

```
Could not launch browser to log in to Steamship.

If you are in Replit:

1) Get an API key at https://steamship.com/account/api
2) Set the STEAMSHIP_API_KEY Replit Secret
3) Close and reopen this shell so that secrets refresh

If you are in a different headless environment, visit https://docs.steamship.com/configuration/authentication.html
Aborted!
Traceback (most recent call last):
  File "/home/mike/GirlfriendGPT/deploy.py", line 15, in <module>
    client = Steamship(workspace=f"girlfriend-ai-{uuid.uuid1()}")
  File "/usr/local/lib/python3.10/dist-packages/steamship/client/steamship.py", line 59, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/steamship/base/client.py", line 84, in __init__
    config = config or Configuration(
  File "/usr/local/lib/python3.10/dist-packages/steamship/base/configuration.py", line 70, in __init__
    api_key = login(
  File "/usr/local/lib/python3.10/dist-packages/steamship/cli/login.py", line 38, in login
    raise SteamshipError(
steamship.base.error.SteamshipError: Could not launch browser to log in to Steamship.

If you are in Replit:

1) Get an API key at https://steamship.com/account/api
2) Set the STEAMSHIP_API_KEY Replit Secret
3) Close and reopen this shell so that secrets refresh

If you are in a different headless environment, visit https://docs.steamship.com/configuration/authentication.html
```

**Comment by billyjbryant** [comment]
Are you running headless?

**Comment by Mikaeel-js** [comment]
idk what headless
i just install and get this result :(

**Comment by EniasCailliau** [comment]
Looks like your cli failed to open a web browser window for you to authenticate. Could you try following the Replit instructions? 

```
1) Get an API key at https://steamship.com/account/api
2) Set the STEAMSHIP_API_KEY Replit Secret
3) Close and reopen this shell so that secrets refresh
```

**Comment by EniasCailliau** [comment]
@Mikaeel-js Did you try it out again?

**Comment by Mikaeel-js** [comment]
I get api from steamship but idk what to do with

I create a .steamship.json in user directory and set it this way 
```
{
  "apiKey": "mykey"
}

```

is this wrong ?

idk why I'm should sign up to replit and set STEAMSHIP_API_KEY Secret

**Comment by Synthintel** [comment]
@billyjbryant @Mikaeel-js 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
