### ISSUE TITLE
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for GirlFriendAIConfig personality   field required (type=value_error.missing)

### ISSUE THREAD

**Issue by ffk123** [EniasCailliau/GirlfriendGPT#42]
getting this error after running python main.py   
  
C:\folder\folder\GirlfriendGPT>python main.py
Traceback (most recent call last):
  File "C:\folder\folder\GirlfriendGPT\main.py", line 56, in <module>
    main()
  File "C:\folder\folder\GirlfriendGPT\main.py", line 26, in main
    agent=GirlfriendGPT(
  File "C:\folder\folder\AppData\Local\Programs\Python\Python310\lib\site-packages\steamship\experimental\package_starters\telegram_bot.py", line 30, in __init__
    super().__init__(**kwargs)
  File "C:\folder\folder\AppData\Local\Programs\Python\Python310\lib\site-packages\steamship\experimental\package_starters\web_bot.py", line 26, in __init__
    super().__init__(**kwargs)
  File "C:\folder\folder\AppData\Local\Programs\Python\Python310\lib\site-packages\steamship\invocable\invocable.py", line 140, in __init__
    self.config = self.config_cls()(**config)
  File "C:\folder\folder\AppData\Local\Programs\Python\Python310\lib\site-packages\steamship\invocable\config.py", line 16, in __init__
    super().__init__(**kwargs)
  File "C:\folder\folder\AppData\Local\Programs\Python\Python310\lib\site-packages\steamship\base\model.py", line 19, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GirlFriendAIConfig

i dont really know what im doing... but any help is appreciated.

**Comment by EniasCailliau** [comment]
Thanks for reporting, just pushed a fix to main for you. Let me know if that resolves things for you :)

**Comment by Synthintel** [comment]
@ffk123 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
