### ISSUE TITLE
Ship Deploy no longer working D:

### ISSUE THREAD

**Issue by sashimirolls** [EniasCailliau/GirlfriendGPT#61]
Done. 📦
Deploying version 9.9 of [luna-sample]... 🚢
It looks like that version [9.9] has already been deployed. Would you like to change the version handle and try again? [Y/n]: y
What should the new version be? Valid characters are a-z, 0-9, . and - [1.0.0]: 10
Deploying version 10 of [luna-sample]... 🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢
Unable to deploy package version.
Server returned message: There was an error loading the main file (it must be named api.py):
Traceback (most recent call last):
  File "/var/task/steamship/invocable/lambda_handler.py", line 301, in safely_find_invocable_class
    module = importlib.import_module("api")
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/api.py", line 30, in <module>
    client = Steamship()
  File "/var/task/steamship/client/steamship.py", line 59, in __init__
    super().__init__(
  File "/var/task/steamship/base/client.py", line 84, in __init__
    config = config or Configuration(
  File "/var/task/steamship/base/configuration.py", line 71, in __init__
    api_key = login(
  File "/var/task/steamship/cli/login.py", line 38, in login
    raise SteamshipError(
steamship.base.error.SteamshipError: Could not launch browser to log in to Steamship.

If you are in Replit:

1) Get an API key at https://steamship.com/account/api
2) Set the STEAMSHIP_API_KEY Replit Secret
3) Close and reopen this shell so that secrets refresh

If you are in a different headless environment, visit https://docs.steamship.com/configuration/authentication.html
Aborted!

**Comment by EniasCailliau** [comment]
Hi could you tell me more about the environment you're running in?

**Comment by joshuaclausen** [comment]
Using Replit in the same way as @sashimirolls

I get the same thing when trying to follow the example in this YouTube video: https://www.youtube.com/watch?v=ShPjYHw_K-U
