### ISSUE TITLE
Steamship Limit Message - already a developer plan subscriber 

### ISSUE THREAD

**Issue by RafaelXYZ-BR** [EniasCailliau/GirlfriendGPT#65]
Hello!

Every time I try to launch python3 api.py or ship deploy && ship use, I got this message, but I already bought the developer plan on Steamship, could you help me? 

ERROR: 

rafaelsantos@Rafaels-MacBook-Pro src % python3 api.py
Starting REPL for Agent...
If you make code changes, restart this REPL. Press CTRL+C to exit at any time.

Input: Hi
[WARNING] Client received error from server: [LimitReached]
You have reached the preview usage limit. Please sign up for a plan at https://steamship.com/account/plan to continue.
[WARNING] Client received error from server: [LimitReached]
You have reached the preview usage limit. Please sign up for a plan at https://steamship.com/account/plan to continue.
steamship.base.error.SteamshipError: [LimitReached]
You have reached the preview usage limit. Please sign up for a plan at https://steamship.com/account/plan to continue.
Traceback (most recent call last):
  File "/Users/rafaelsantos/Desktop/GirlfriendGPT-main/src/api.py", line 140, in <module>
    ).run()
      ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/utils/repl.py", line 145, in run
    self.run_with_client(client, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/utils/repl.py", line 140, in run_with_client
    response = responder(input_text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rafaelsantos/Desktop/GirlfriendGPT-main/src/agent/base.py", line 132, in prompt
    context = AgentContext.get_or_create(self.client, {"id": str(uuid.uuid4())})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/agents/schema/context.py", line 55, in get_or_create
    history = ChatHistory.get_or_create(client, context_keys, tags, searchable=searchable)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/agents/schema/chathistory.py", line 91, in get_or_create
    file = ChatHistory._get_existing_file(client, context_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/agents/schema/chathistory.py", line 47, in _get_existing_file
    file = File.query(client, file_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/data/file.py", line 223, in query
    res = client.post(
          ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/base/client.py", line 573, in post
    return self.call(
           ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/steamship/base/client.py", line 531, in call
    raise error
steamship.base.error.SteamshipError: [LimitReached]
You have reached the preview usage limit. Please sign up for a plan at https://steamship.com/account/plan to continue.

**Comment by EniasCailliau** [comment]
Huh. Can you try re-authenticating by running `ship login` from your CLI?

**Comment by RafaelXYZ-BR** [comment]
> Huh. Can you try re-authenticating by running `ship login` from your CLI?

It worked, thank you so much for the help.

**Comment by RafaelXYZ-BR** [comment]
Also, is there a way to disable the "how can I help you today" line?

This is line is so unrealistic for me, I think it would better without it.

**Comment by talhaanwarch** [comment]
I am facing this issue too and `ship login` did not worked for me
